### PR TITLE
feat: allow create cost center with an user provided id

### PR DESCRIPTION
**Pull request by enzomerca**
#### What problem is this solving?
The existing `createCostCenter` graphql API does not allow creating a cost center with an user provided id. This PR allows that. This API still works without providing an ID, so the admin UI use case should not break.

This will allow us to create cost centers with user provided ids on the bulk import application.

#### How to test it?
1. Create a new cost center using the admin UI. It should work as before (and id will be automatically created for the cost center).
2. Call the `createCostCenter` graphql api providing the cost center id. It should also work if the id is not provided. The request looks like this:
```
curl --location 'https://b2bteam1399--b2bstoreqa.myvtex.com/_v/private/graphql/v1' \
--header 'Cookie: VtexIdclientAutCookie=<cookie>; janus_sid=1e52fe67-97ef-4793-9c3d-e6075f17a2e0' \
--header 'Content-Type: application/json' \
--data-raw '{"query":"mutation CreateCostCenter($organizationId: ID, $input: CostCenterInput!) {\n  createCostCenter(organizationId: $organizationId, input: $input)\n    @context(provider: \"vtex.b2b-organizations-graphql\") {\n    id\n  }\n}","variables":{
  "organizationId": "enzo-org-test",
  "input": {
    "id": "third-cost-center-id"
    "name": "Third",
    "addresses": [{
    "addressId": "0",
    "addressType": "residential",
    "city": "São Paulo",
    "complement": null,
    "country": "BRA",
    "receiverName": "principal",
    "geoCoordinates": [
        -46.630714416503906,
        -23.55284881591797
    ],
    "neighborhood": "Sé",
    "number": "1",
    "postalCode": "01001-000",
    "reference": null,
    "state": "SP",
    "street": "Praça da Sé",
    "addressQuery": ""
    }],
    "phoneNumber": "",
    "businessDocument": "",
    "customFields": [],
    "stateRegistration": ""
  }
}}'
```

And here is the expected response when providing the id:
```
{
    "data": {
        "createCostCenter": {
            "id": "third-cost-center-id"
        }
    }
}
```

and when not providing the id it should look like this:
```
{
    "data": {
        "createCostCenter": {
            "id": "fcd4957d-7e46-11ee-83ab-12ecbcbe50e3"
        }
    }
}
```
[Workspace](https://b2bteam1399--b2bstoreqa.myvtex.com/admin)

### CODE REVIEW

**Review by mairatma — DISMISSED** [review]
Lgtm! 

Just curious, what happens if the caller provides an id that already exists? I assume we throw an error?

**Comment by mairatma** [comment]
Just make sure to select the right version bump in the bot's post further above in this PR. Since this adds a new field it should probably be a minor bump.

**Comment by enzomerca** [comment]
> Lgtm!
> 
> Just curious, what happens if the caller provides an id that already exists? I assume we throw an error?

It returns this error (not great as it has no indication that it is because the id already exists, and also it says "Request failed with status code 400" but there is a code = INTERNAL_SERVER_ERROR ... but at least it returns an error!):
```
{
    "data": {
        "createCostCenter": null
    },
    "errors": [
        {
            "message": "Request failed with status code 400",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "vtex_b2borganizationsgraphql_0_44_0_createCostCenter"
            ],
            "extensions": {
                "message": "Request failed with status code 400",
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "message": "Request failed with status code 400",
                    "name": "Error",
                    "extensions": {
                        "message": "Request failed with status code 400"
                    },
                    "sensitive": {
                        "stack": "Error: Request failed with status code 400\n    at createCostCenter (/usr/src/node/resolvers/Mutations/CostCenters.ts:80:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at runHttpQuery (/usr/local/data/service/node_modules/@vtex/api/lib/service/worker/runtime/graphql/middlewares/run.js:8:22)\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/time.js:79:13\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/cancel.js:9:9\n    at parseAndValidateQuery (/usr/local/data/service/node_modules/@vtex/api/lib/service/worker/runtime/graphql/middlewares/query.js:51:5)\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/time.js:79:13\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/cancel.js:9:9\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/time.js:79:13\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/cancel.js:9:9\n    at graphqlError (/usr/local/data/service/node_modules/@vtex/api/lib/service/worker/runtime/graphql/middlewares/error.js:47:9)\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/time.js:79:13\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/cancel.js:9:9\n    at response (/usr/local/data/service/node_modules/@vtex/api/lib/service/worker/runtime/graphql/middlewares/response.js:23:5)\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/time.js:79:13\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/cancel.js:9:9\n    at injectGraphqlContext (/usr/local/data/service/node_modules/@vtex/api/lib/service/worker/runtime/graphql/middlewares/context.js:14:5)\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/time.js:79:13\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/cancel.js:9:9\n    at updateRunnableSchema (/usr/local/data/service/node_modules/@vtex/api/lib/service/worker/runtime/graphql/middlewares/updateSchema.js:27:5)\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/time.js:79:13\n    at /usr/local/data/service/node_modules/@vtex/api/lib/utils/cancel.js:9:9"
                    }
                }
            },
            "positions": [
                113
            ],
            "name": "GraphQLError",
            "source": {
                "body": "mutation CreateCostCenter($organizationId: ID, $input: vtex_b2borganizationsgraphql_0_44_0_CostCenterInput!) {\n  createCostCenter: vtex_b2borganizationsgraphql_0_44_0_createCostCenter(organizationId: $organizationId, input: $input) {\n    id: vtex_b2borganizationsgraphql_0_44_0_id\n  }\n}\n",
                "name": "GraphQL request",
                "locationOffset": {
                    "line": 1,
                    "column": 1
                }
            },
            "operationId": "d6a0fc5c-1692-4bb0-ad6a-d90d842eda89",
            "requestId": "14698fdfd3d8415e92ebd487e1793d7c"
        }
    ]
}
```

**Comment by enzomerca** [comment]
> > It returns this error (not great as it has no indication that it is because the id already exists, and also it says "Request failed with status code 400" but there is a code = INTERNAL_SERVER_ERROR ... but at least it returns an error!):
> 
> Oh wow, we're returning the whole stack trace there, that's not good. It's not your fault though, at least we're throwing a 400 error. We can add something to the backlog for improving these errors (removing the stack trace and giving better error messages for known use cases like this one, for example).

I decided to create another graphql API specifically for this, so now we have the proper errors for when the organization ID does not exists and for when the cost center already exists!

**Review by Rudge — APPROVED** [review]

**Comment by enzomerca** [comment]
Holding this change until after black friday 2023.

**Pull request merged**
